version: '3.7'
services:
  k3s:
    image: rancher/k3s:v1.29.1-k3s1
    privileged: true
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - ./exploit:/exploit
    command: server
    networks:
      - kind
    ports:
      - 80:80
      - 443:443
networks:
  kind:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
